name = "sigmadoc"
license = "MIT"
licenselink = "https://github.com/bradleyjkemp/sigmadoc/blob/master/LICENSE"
description = ""
homepage = "https://github.com/bradleyjkemp/sigmadoc"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Bradley Kemp"
  homepage = "https://bradleyjkemp.dev"
